### ISSUE TITLE
None needed replace when updating: aks_authorized_ips

### ISSUE THREAD

**Issue by NissesSenap** [XenitAB/terraform-modules#438] opened 2021-11-05 08:59 UTC
When updating aks_authorized_ips we get the following output.
This can happen when aks_authorized_ips contains ip:s without netmask on them but in this case
it's defined.

We think this is a upstream issue and azure_rm shouldn't react the way it does.
Do some research, create a issue upstream and see if it can get solved.

```hcl
-/+ resource "azurerm_role_assignment" "aks_managed_identity_noderg_managed_identity_operator" {
      ~ id                               = "/subscriptions/sub-id/resourceGroups/rg-name_westeurope/providers/Microsoft.Authorization/roleAssignments/roleAssignmentsID" -> (known after apply)
      ~ name                             = "roleAssignmentsID" -> (known after apply)
      ~ principal_type                   = "Group" -> (known after apply)
      ~ role_definition_id               = "/subscriptions/sub-id/providers/Microsoft.Authorization/roleDefinitions/somee-id" -> (known after apply)
      ~ scope                            = "/subscriptions/sub-id/resourceGroups/rg-name_westeurope" -> (known after apply) # forces replacement
      + skip_service_principal_aad_check = (known after apply)
        # (2 unchanged attributes hidden)
    }
```

**Comment by landerss1** [comment] 2024-08-16 05:57
Can't reproduce. Closing.

**Closed by landerss1** 2024-08-16 05:57 UTC
